In [56]:
#import đồ
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import torch
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu


In [57]:
#load dataset
dataset= pd.read_csv("C://Users//vutuan//Desktop//My-Projects//Machine Learning//Datasets//Medical-Cost-Personal-Datasets.csv")
dataset

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [58]:
#chọn feature
X= dataset.iloc[:,[0,1,2,3,6]].values
y= dataset.iloc[:,[4]].values

print(X,y)

[[19 'female' 27.9 0 16884.924]
 [18 'male' 33.77 1 1725.5523]
 [28 'male' 33.0 3 4449.462]
 ...
 [18 'female' 36.85 0 1629.8335]
 [21 'female' 25.8 0 2007.945]
 [61 'female' 29.07 0 29141.3603]] [['yes']
 ['no']
 ['no']
 ...
 ['no']
 ['no']
 ['yes']]


In [59]:
#encoding data
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        if(X[i][j]=='female'):
            X[i][j]=0.
        if(X[i][j]=='male'):
            X[i][j]=1.
            
for i in range(y.shape[0]):
    for j in range(y.shape[1]):
        if(y[i][j]=='no'):
            y[i][j]=0
        if(y[i][j]=='yes'):
            y[i][j]=1
            
X = X.astype('float64')
y = y.astype('float64')
print(X)
print(y)

[[1.90000000e+01 0.00000000e+00 2.79000000e+01 0.00000000e+00
  1.68849240e+04]
 [1.80000000e+01 1.00000000e+00 3.37700000e+01 1.00000000e+00
  1.72555230e+03]
 [2.80000000e+01 1.00000000e+00 3.30000000e+01 3.00000000e+00
  4.44946200e+03]
 ...
 [1.80000000e+01 0.00000000e+00 3.68500000e+01 0.00000000e+00
  1.62983350e+03]
 [2.10000000e+01 0.00000000e+00 2.58000000e+01 0.00000000e+00
  2.00794500e+03]
 [6.10000000e+01 0.00000000e+00 2.90700000e+01 0.00000000e+00
  2.91413603e+04]]
[[1.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [1.]]


In [74]:
#chia data thành train và test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=3)
#chuyển thành mảng tensor
X_train = tf.convert_to_tensor(X_train)
X_test = tf.convert_to_tensor(X_test)
print(X_test,y_test)

tf.Tensor(
[[3.30000000e+01 1.00000000e+00 3.52450000e+01 0.00000000e+00
  1.24048791e+04]
 [4.60000000e+01 0.00000000e+00 2.77200000e+01 1.00000000e+00
  8.23263880e+03]
 [1.90000000e+01 0.00000000e+00 2.89000000e+01 0.00000000e+00
  1.74321400e+03]
 ...
 [5.70000000e+01 1.00000000e+00 2.37000000e+01 0.00000000e+00
  1.09593300e+04]
 [2.50000000e+01 1.00000000e+00 2.62200000e+01 0.00000000e+00
  2.72132080e+03]
 [1.80000000e+01 0.00000000e+00 3.82800000e+01 0.00000000e+00
  1.41330377e+04]], shape=(536, 5), dtype=float64) [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0

In [93]:
#cài đạt mạng neuron
model = Sequential(
    [               
        tf.keras.Input(shape=(5,)),
        Dense(11, activation='relu'),
        Dense(1, activation='sigmoid'),

    ], 
)

In [94]:
#chọn loss functin và optimizer
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0003),
)

In [95]:
#thông tin mạng neuron
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_28 (Dense)            (None, 11)                66        
                                                                 
 dense_29 (Dense)            (None, 1)                 12        
                                                                 
Total params: 78
Trainable params: 78
Non-trainable params: 0
_________________________________________________________________


In [96]:
history = model.fit(
    X_train,y_train,
    epochs=100
)

Epoch 1/100
26/26 [==============================] - 1s 1ms/step - loss: 1951.7333
Epoch 2/100
26/26 [==============================] - 0s 1ms/step - loss: 1753.9596
Epoch 3/100
26/26 [==============================] - 0s 2ms/step - loss: 1559.6055
Epoch 4/100
26/26 [==============================] - 0s 1ms/step - loss: 1357.6161
Epoch 5/100
26/26 [==============================] - 0s 1ms/step - loss: 1160.3219
Epoch 6/100
26/26 [==============================] - 0s 3ms/step - loss: 964.7737
Epoch 7/100
26/26 [==============================] - 0s 1ms/step - loss: 766.1711
Epoch 8/100
26/26 [==============================] - 0s 1ms/step - loss: 547.7864
Epoch 9/100
26/26 [==============================] - 0s 1ms/step - loss: 334.8395
Epoch 10/100
26/26 [==============================] - 0s 1ms/step - loss: 124.2017
Epoch 11/100
26/26 [==============================] - 0s 1ms/step - loss: 47.2807
Epoch 12/100
26/26 [==============================] - 0s 1ms/step - loss: 43.5335
Epoch 13/1

In [97]:
pred=model.predict(X_test)
for i in range(pred.shape[0]):
    for j in range(pred.shape[1]):
        if(pred[i][j]>=0.5):
            pred[i][j]=1
        if(pred[i][j]<=0.5):
            pred[i][j]=0
y_hat=np.hstack((y_test,pred))
err=0
cor=0
for i in range(y_hat.shape[0]):
    if(y_hat[i][0]!=y_hat[i][1]):
        err+=1
    else:
        cor+=1
print('số lỗi:',err)
print('chính xác:',cor)
print(y_hat)


17/17 [==============================] - 0s 686us/step
số lỗi: 24
chính xác: 512
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
